### ISSUE TITLE
dotENV File Secret Keys question for clarification

### ISSUE THREAD

**Issue by wayneburlingame** [staart/ui#874]
**Hello,**

In the .ENV file,
In the lines section:

###  # Secret keys for encryption :secret:
`JWT_SECRET = "staart"`
`JWT_ISSUER = "staart"`
`SERVICE_2FA = "staart"`
`HASH_IDS = "staart" `

:question: Can we just put in replacement of "staart" some long random strings :blowfish:  on all 4 of these entries? :thinking:

I was not sure if we needed to do something like register somewhere like we do with MaxMind Keys. :dizzy_face:

Thank you,

                Wayne

**Comment by AnandChowdhary** [comment]
Yes, `"staart"` is the default, but it's recommended that you change the JWT secret to be a long, unique string. For JWT issuer and 2FA service, you should put the name of your app, because users may see this. For hash IDs, you can also add a unique string because it's used as the salt when generating IDs.

**Comment by FindingAnand** [comment]
⚠️ This issue has not seen any activity in the past 2 months so I'm marking it as stale. I'll close it if it doesn't see any activity in the coming week.
